steps:
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/projectz-239507/app', '.']
  # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/projectz-239507/app']
  # Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'app', '--image', 'gcr.io/projectz-239507/app', '--region', 'us-central1']
  # Create a Cloud Bucket - Test
# - name: 'gcr.io/cloud-builders/gsutil'
#   args: ['mb', '-l', 'us-east1', 'gs://newtitanbucket']
  # Create User DB
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['sql', 'databases', 'create', 'newdatabase', '--instance', 'autotitan']
images:
- gcr.io/projectz-239507/app
timeout: 1200s

# Remember to activate permissions on Service Account